#!/bin/bash
# SPDX-License-Identifier: GPL-2.0
#
# scripts/kconfig.sh — 简化的 Kconfig 解析器
#
# 原理：
#   读取 Kconfig 文件中的 config 条目，提取其默认值，
#   生成 make 可 include 的 include/config/auto.conf。
#
#   当前实现：写入硬编码默认值（与 Kconfig 中 default 一致）。
#   后续可扩展为完整 Kconfig 解析器。
#
# 参考：Linux 7.1.3 scripts/kconfig/

SRCTREE="${1:-.}"
KCONFIG="${SRCTREE}/Kconfig"
AUTOCONF="${SRCTREE}/include/config/auto.conf"

if [ ! -f "$KCONFIG" ]; then
    echo "Error: Kconfig not found at $KCONFIG" >&2
    exit 1
fi

mkdir -p "$(dirname "$AUTOCONF")"

# 写入默认配置（值与 Kconfig 中 default 声明一致）
{
    printf '#\n'
    printf '# Automatically generated by scripts/kconfig.sh\n'
    printf '#\n'
    printf 'CONFIG_T001_VERSION="0.1.0"\n'
    printf 'CONFIG_SERIAL_DEBUG=y\n'
    printf '# CONFIG_FRAMEBUFFER_DEBUG is not set\n'
    printf 'CONFIG_FRAMEBUFFER=y\n'
    printf 'CONFIG_TTY=y\n'
    printf 'CONFIG_KSTRING=y\n'
    printf 'CONFIG_VSPRINTF=y\n'
} > "$AUTOCONF"

echo "Configuration written to $AUTOCONF" >&2
